### ISSUE TITLE
render function is down

### ISSUE THREAD

**Issue by ashtonteng** [matthiaskoenig/libsbgn-python#32] opened 2020-03-15 07:04 UTC
I believe the service that `render_sbgn` relies on is down, do you have any recommendations for alternate ways to render these maps? Thanks!

**Comment by matthiaskoenig** [comment] 2020-03-15 22:14
Hi @ashtonteng.
This is a duplicate of #32, I will take care of this.
Best Matthias

**Closed as completed** 2020-03-16 17:01 UTC
